### ISSUE TITLE
popcorntimes.tv crashing on Kodi Matrix

### ISSUE THREAD

**Issue by V10lator** [dh4rry/kodiAddons#5]
```
2020-12-27 15:27:24.984 T:5136    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2020-12-27 15:27:25.026 T:8898     INFO <general>: initializing python engine.
2020-12-27 15:27:27.330 T:8898     INFO <general>: CPythonInvoker(6, /storage/.kodi/addons/plugin.video.popcorntimes/main.py): script successfully run
2020-12-27 15:27:27.787 T:8898     INFO <general>: Python interpreter stopped
2020-12-27 15:27:29.758 T:8905     INFO <general>: initializing python engine.
2020-12-27 15:27:37.163 T:8905     INFO <general>: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.popcorntimes/main.py): script successfully run
2020-12-27 15:27:37.578 T:8905     INFO <general>: Python interpreter stopped
2020-12-27 15:28:14.770 T:8938     INFO <general>: initializing python engine.
2020-12-27 15:28:17.191 T:8938     INFO <general>: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.popcorntimes/main.py): script successfully run
2020-12-27 15:28:17.602 T:8938     INFO <general>: Python interpreter stopped
2020-12-27 15:28:21.147 T:8945     INFO <general>: initializing python engine.
2020-12-27 15:28:24.713 T:8945     INFO <general>: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.popcorntimes/main.py): script successfully run
2020-12-27 15:28:25.150 T:8945     INFO <general>: Python interpreter stopped
2020-12-27 15:30:07.449 T:9001     INFO <general>: initializing python engine.
2020-12-27 15:30:09.555 T:9001    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'LOGNOTICE'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.popcorntimes/main.py", line 163, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.popcorntimes/main.py", line 154, in router
                                                       play(params['url'])
                                                     File "/storage/.kodi/addons/plugin.video.popcorntimes/main.py", line 124, in play
                                                       streamUrl = getStream(movie_url)
                                                     File "/storage/.kodi/addons/plugin.video.popcorntimes/main.py", line 65, in getStream
                                                       xbmc.log("encoded:" + encoded, level=xbmc.LOGNOTICE)
                                                   AttributeError: module 'xbmc' has no attribute 'LOGNOTICE'
                                                   -->End of Python script error report<--
                                                   
2020-12-27 15:30:09.946 T:9001     INFO <general>: Python interpreter stopped
2020-12-27 15:30:09.963 T:5136    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.popcorntimes/?action=play&url=https%3A%2F%2Fpopcorntimes.tv%2Fde%2Fm%2F1IW1rFEq%2Fnotlandung-im-weltraum]
```
AFAIK `LOGNOTICE` has been replaced with `LOGINFO`. Not sure if there are more showstoppers.

**Comment by V10lator** [comment]
I just checked: No more crashes when changing
```
xbmc.log("encoded:" + encoded, level=xbmc.LOGNOTICE)
```
to
```
xbmc.log("encoded:" + encoded, level=xbmc.LOGINFO)
```
at `.kodi/addons/plugin.video.popcorntimes/main.py`
